#= require jquery
#= require jquery.turbolinks
#= require jquery_ujs
#= require turbolinks
#= require bootstrap/alert
#= require bootstrap/dropdown
#= require bootstrap/collapse
#= require lodash
#= require vue
#= require vue_extensions
#= require selectize/standalone/selectize
#= require algoliasearch/algoliasearchLite
#= require comments
#= require ideas
#= require main
#= require votes
#= require backer_votes
#= require_self
